// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA2aWHO86MQOmD2yQtFsuCbL-mJyh3LRis',
    appId: '1:1074514980996:web:9e2f94ddc16dfc57bc52d1',
    messagingSenderId: '1074514980996',
    projectId: 'flutter-login-app-2024',
    authDomain: 'flutter-login-app-2024.firebaseapp.com',
    storageBucket: 'flutter-login-app-2024.appspot.com',
    measurementId: 'G-JBFKBWPYQV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDct4bgoRuId_4h2wyLCBUDst0VO-7Xblg',
    appId: '1:1074514980996:android:0a47bc7b7344c129bc52d1',
    messagingSenderId: '1074514980996',
    projectId: 'flutter-login-app-2024',
    storageBucket: 'flutter-login-app-2024.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMJ_QTdFetyZJOHgiTlr6_zvUWBfsBvfA',
    appId: '1:1074514980996:ios:c80709c7238cde20bc52d1',
    messagingSenderId: '1074514980996',
    projectId: 'flutter-login-app-2024',
    storageBucket: 'flutter-login-app-2024.appspot.com',
    iosBundleId: 'com.takuro.ientrance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMJ_QTdFetyZJOHgiTlr6_zvUWBfsBvfA',
    appId: '1:1074514980996:ios:7d878743ac4a153cbc52d1',
    messagingSenderId: '1074514980996',
    projectId: 'flutter-login-app-2024',
    storageBucket: 'flutter-login-app-2024.appspot.com',
    iosBundleId: 'com.takuro.ientrance.RunnerTests',
  );
}
